### ISSUE TITLE
Error level logging too verbose

### ISSUE THREAD

**Issue by clintkev251** [Paxxs/traefik-get-real-ip#4]
Deployed this the other day and its working really well other than one minor annoyance. It seems like every evaluation is being logged to the error level which completely takes over my logs and makes it harder to track down other issues. This logging could be nice to have when first setting things up, but it would be nice if they were moved to maybe an info or debug level as to not clog up the error level once its deployed and working

**Comment by Paxxs** [comment]
I changed the behavior in version 1.0.1.
Now logs will be output at debug level.

thanks for u feedback！

```yml
experimental:
  plugins:
    real-ip:
      moduleName: github.com/Paxxs/traefik-get-real-ip
      version: v1.0.1
```
